#!/usr/bin/env python3
"""Auto-generate the canonical tables in SPEC.md.

Five tables, each spliced between <!-- AUTO:<name> BEGIN --> and <!-- AUTO:<name> END --> markers:

  AUTO:workflows     §5  — all .github/workflows/*.yml entries
  AUTO:wall-endpoints   §11.8.6  — handleWall() actions
  AUTO:holidays-endpoints  §11.9.4  — handleHolidays() actions

The §3 Pages and §6 Scanner tables are NOT auto-generated yet because they
carry hand-written one-paragraph descriptions per row that don't live in
code. They stay manual until we encode that description somewhere durable
(e.g. a header docstring convention).

Rule: this script is non-destructive. It only rewrites the content between
the BEGIN/END markers. The prose around the tables is hand-written and
preserved. If a marker block is missing, the script exits non-zero and
prints the file + marker name — that's a signal that someone deleted the
markers and the manual table now has a drift risk.

Run: python3 scripts/generate_canonical_tables.py
"""
from __future__ import annotations

import os
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SPEC_PATH = REPO_ROOT / "SPEC.md"
WORKFLOWS_DIR = REPO_ROOT / ".github" / "workflows"
WORKER_PATH = REPO_ROOT / "worker" / "workspace-worker.js"

CRON_RE = re.compile(r"cron:\s*['\"]([^'\"]+)['\"]")
SECRET_RE = re.compile(r"\$\{\{\s*secrets\.([A-Z0-9_]+)\s*\}\}")
NAME_RE = re.compile(r"^name:\s*(.+)$", re.MULTILINE)


def humanise_cron(cron: str) -> str:
    """Approximate human-readable. Good for the kinds of crons we use."""
    parts = cron.strip().split()
    if len(parts) != 5:
        return f"`{cron}`"
    m, h, dom, mon, dow = parts
    # Hourly window: 0 6-23 * * *  → "hourly 06-23 UTC :00"
    if m.isdigit() and "-" in h and dom == "*" and mon == "*" and dow == "*":
        return f"hourly {h} UTC :{m.zfill(2)}"
    # Single-time-of-day: 5 7 * * *  → "daily 07:05 UTC"
    if m.isdigit() and h.isdigit() and dom == "*" and mon == "*" and dow == "*":
        return f"daily {h.zfill(2)}:{m.zfill(2)} UTC"
    # Every N hours: 20 */6 * * *  → "every 6h, :20"
    if m.isdigit() and h.startswith("*/"):
        return f"every {h[2:]}h, :{m.zfill(2)} UTC"
    # Day-of-month: 0 9 1 * *  → "monthly 09:00 on the 1st"
    if m.isdigit() and h.isdigit() and dom.isdigit() and mon == "*":
        return f"monthly {h.zfill(2)}:{m.zfill(2)} UTC on day {dom}"
    return f"`{cron}`"


def workflow_row(path: Path) -> dict | None:
    text = path.read_text()
    name_m = NAME_RE.search(text)
    name = name_m.group(1).strip() if name_m else path.stem
    crons = CRON_RE.findall(text)
    has_dispatch = "workflow_dispatch" in text
    has_push = re.search(r"^\s*push:\s*$", text, re.MULTILINE) is not None
    has_pr = re.search(r"^\s*pull_request:", text, re.MULTILINE) is not None
    has_schedule = bool(crons)

    if has_schedule:
        cadence = " · ".join(humanise_cron(c) for c in crons)
        if has_dispatch:
            cadence += " (+manual)"
    elif has_push or has_pr:
        triggers = []
        if has_push: triggers.append("push to main")
        if has_pr:   triggers.append("pull request")
        cadence = " / ".join(triggers)
    elif has_dispatch:
        cadence = "manual only"
    else:
        cadence = "(no trigger)"

    secrets = sorted(set(SECRET_RE.findall(text)))
    return {
        "file": path.name,
        "name": name,
        "cadence": cadence,
        "secrets": secrets,
    }


def render_workflow_table() -> str:
    rows = []
    for p in sorted(WORKFLOWS_DIR.glob("*.yml")):
        row = workflow_row(p)
        if row:
            rows.append(row)
    out = [
        "| Workflow | Cadence (UTC) | Secrets it uses |",
        "|---|---|---|",
    ]
    for r in rows:
        secs = ", ".join(f"`{s}`" for s in r["secrets"]) or "—"
        cadence = r["cadence"].replace("|", "\\|")
        out.append(f"| `{r['file']}` | {cadence} | {secs} |")
    out.append("")
    out.append(f"_{len(rows)} workflows total. Generated by `scripts/generate_canonical_tables.py` — don't hand-edit between the AUTO markers._")
    return "\n".join(out)


# --- Worker endpoints ---

def render_endpoint_table(handler_name: str, route_prefix: str) -> str:
    """Walk worker/workspace-worker.js, find the `handle<X>` function, extract
    its `case "<action>":` arms inside the switch."""
    src = WORKER_PATH.read_text()
    # Find the function body. Use a simple bracket-matched extraction.
    m = re.search(rf"async function {handler_name}\([^)]*\)\s*\{{", src)
    if not m:
        sys.exit(f"error: can't find {handler_name} in {WORKER_PATH}")
    start = m.end()
    depth = 1
    i = start
    while i < len(src) and depth > 0:
        c = src[i]
        if c == "{": depth += 1
        elif c == "}": depth -= 1
        i += 1
    body = src[start:i]
    # Find every case "<action>": ...
    cases = re.findall(r'case\s+"([a-z][a-z0-9_-]+)"\s*:\s*([^\n]+)', body)
    # Whoami is usually outside the switch — grab it separately.
    has_whoami = bool(re.search(r'action\s*===\s*"whoami"', body))
    rows = [
        "| Path | Method | Notes |",
        "|---|---|---|",
    ]
    if has_whoami:
        rows.append(f"| `{route_prefix}/whoami` | GET or POST | Returns `{{ ok, email, name }}` for the signed-in viewer. |")
    for action, line in cases:
        # Trim "return json(await wallPost(...), 200, req);" → "wallPost"
        fn_m = re.search(r"await\s+(\w+)\(", line)
        helper = fn_m.group(1) if fn_m else "—"
        rows.append(f"| `{route_prefix}/{action}` | POST | Body handled by `{helper}()` in `worker/workspace-worker.js`. |")
    rows.append("")
    rows.append(f"_{len(cases) + (1 if has_whoami else 0)} endpoints. Generated by `scripts/generate_canonical_tables.py` from `{handler_name}()` in `worker/workspace-worker.js`._")
    return "\n".join(rows)


# --- Splicer ---

def splice(text: str, marker: str, body: str) -> tuple[str, bool]:
    begin = f"<!-- AUTO:{marker} BEGIN -->"
    end   = f"<!-- AUTO:{marker} END -->"
    pattern = re.compile(re.escape(begin) + r".*?" + re.escape(end), re.DOTALL)
    if not pattern.search(text):
        sys.exit(f"error: SPEC.md missing {begin}…{end} block. Add the markers around the table this script manages.")
    new_block = f"{begin}\n\n{body}\n\n{end}"
    new_text = pattern.sub(new_block, text)
    return new_text, new_text != text


def main():
    text = SPEC_PATH.read_text()
    sections = [
        ("workflows",          render_workflow_table()),
        ("wall-endpoints",     render_endpoint_table("handleWall",     "/api/wall")),
        ("holidays-endpoints", render_endpoint_table("handleHolidays", "/api/holidays")),
    ]
    changed_any = False
    for marker, body in sections:
        text, changed = splice(text, marker, body)
        print(f"  AUTO:{marker:<22} {'updated' if changed else 'unchanged'}", flush=True)
        changed_any = changed_any or changed
    if changed_any:
        SPEC_PATH.write_text(text)


if __name__ == "__main__":
    main()
